### ISSUE TITLE
Unable to run tasks on 2024.1.12 macos-arm64

### ISSUE THREAD

**Issue by yshalsager** [jdx/mise#1399]
**Describe the bug**

```
RUST_BACKTRACE=full mise r dev-client
thread 'main' panicked at src/path_env.rs:39:35:
called `Result::unwrap()` on an `Err` value: JoinPathsError { inner: JoinPathsError }
stack backtrace:
   0:        0x104d45dd0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hade97c44b56fc870
   1:        0x1048c607c - core::fmt::write::h81cbefbffc581dab
   2:        0x104d52ffc - std::io::Write::write_fmt::h125c60058ebfe43c
   3:        0x104d45bd8 - std::sys_common::backtrace::print::hfa54be0dd0cf5860
   4:        0x104d5898c - std::panicking::default_hook::{{closure}}::h4235e0929057f079
   5:        0x104d593f4 - std::panicking::rust_panic_with_hook::h1767d40d669aa9fe
   6:        0x104d46124 - std::panicking::begin_panic_handler::{{closure}}::h83ff281d56dc913c
   7:        0x104d46090 - std::sys_common::backtrace::__rust_end_short_backtrace::h2f399e8aa761a4f1
   8:        0x104d58d70 - _rust_begin_unwind
   9:        0x104ea2468 - core::panicking::panic_fmt::hc32404f2b732859f
  10:        0x104ea238c - core::result::unwrap_failed::h2ea3b6e22f1f6a7c
  11:        0x1049af4f4 - mise::toolset::Toolset::env_with_path::hbacf154b7512dd36
  12:        0x104ae39e0 - mise::cli::run::Run::run::h5d80456549b1a4e7
  13:        0x10484df24 - mise::cli::Cli::run::h117c566d01c4ec18
  14:        0x104aba1a0 - mise::main::hd128539a74ffbb06
  15:        0x1047ff24c - std::sys_common::backtrace::__rust_begin_short_backtrace::h9e2e35f5de64a38c
  16:        0x104ac293c - std::rt::lang_start::h2d3b8b22608cdab6
  17:        0x104ab9d84 - _main
  ```

**To Reproduce**
Run any task defined in toml.

```toml
[tasks.dev-client]
description = 'Start client'
run = 'pnpm -C client run dev'
```

**Expected behavior**
Running the task. It was working fine before the update.

**`mise doctor` output**

```text
mise version:
  2024.1.12 macos-arm64 (2024-01-07)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Sun, 7 Jan 2024 13:15:45 +0000
  Rust Version: rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

mise data directory:
  /Users/yshalsager/.local/share/mise

mise environment variables:
  MISE_SHELL=zsh

mise settings file:
  ~/.config/mise/settings.toml

settings:
  {
    "all_compile": false,
    "always_keep_download": false,
    "always_keep_install": false,
    "asdf_compat": false,
    "color": true,
    "disable_default_shorthands": false,
    "disable_tools": [],
    "experimental": true,
    "jobs": 4,
    "legacy_version_file": true,
    "legacy_version_file_disable_tools": [],
    "node_compile": false,
    "not_found_auto_install": true,
    "paranoid": false,
    "plugin_autoupdate_last_check_duration": "7d",
    "python_compile": false,
    "python_venv_auto_create": true,
    "raw": false,
    "shorthands_file": null,
    "task_output": null,
    "trusted_config_paths": [],
    "quiet": false,
    "verbose": false,
    "yes": false,
    "ci": false,
    "cd": null,
    "debug": false,
    "env_file": null,
    "trace": false,
    "log_level": "info"
  }

config files:
  /Users/yshalsager/.tool-versions
  /Users/yshalsager/.config/mise/config.toml
  /Users/yshalsager/Projects/xyz/.mise.toml
  /Users/yshalsager/Projects/xyz.mise.local.toml

plugins:
  bun          (core)
  deno         (core)
  erlang       (core)
  go           (core)
  hugo         https://github.com/NeoHsu/asdf-hugo.git#125ce37
  java         (core)
  lazygit      https://github.com/nklmilojevic/asdf-lazygit.git#78e04f1
  node         (core)
  pipx         https://github.com/yozachar/asdf-pipx.git#81cb547
  pnpm         https://github.com/jonathanmorley/asdf-pnpm.git#305baff
  poetry       https://github.com/rtx-plugins/rtx-poetry.git#916c061
  pre-commit   https://github.com/jonathanmorley/asdf-pre-commit.git#26bfc42
  python       (core)
  rclone       https://github.com/johnlayton/asdf-rclone.git#6d0fb47
  ruby         (core)
  yarn         https://github.com/twuni/asdf-yarn.git#376c540

toolset:
  python@3.12, poetry@latest, node@20, pnpm@8, pre-commit@latest, yarn@1.22.19, pipx@latest, lazygit@latest, rclone@latest

No problems found
```

**Comment by yshalsager** [comment]
@fiadliel I have tried with no env configurations at all, still the same.

**Comment by jdx** [comment]
do you have any strange characters in PATH? what's the output of `mise env`?

**Comment by yshalsager** [comment]
> do you have any strange characters in PATH? what's the output of `mise env`?

The full path is `~/Projects/for-others/a/b`

`mise env` gives the same error.

I have just tried another project I use mise for, tasks run without errors. So I started removing lines from toml config to see what causes the problem, it started working after removing `poetry = { version = 'latest', pyproject = 'pyproject.toml' }` line.

**Comment by yshalsager** [comment]
@jdx here's the full trace

```
++ setup_virtualenv
+++ poetry_venv
+++ local pyproject
++++ eval 'echo pyproject.toml'
+++++ echo pyproject.toml
+++ pyproject=pyproject.toml
+++ '[' pyproject.toml = '' ']'
+++ [[ pyproject.toml != /* ]]
+++ [[ -n /Users/yshalsager/Projects/for-others/a/b ]]
+++ pyproject=/Users/yshalsager/Projects/for-others/a/b/pyproject.toml
+++ [[ ! -f /Users/yshalsager/Projects/for-others/a/b/pyproject.toml ]]
++++ poetry_bin
++++ echo /Users/yshalsager/.local/share/mise/installs/poetry/1.7.1/bin/poetry
+++ /Users/yshalsager/.local/share/mise/installs/poetry/1.7.1/bin/poetry env info --path
+++ true
++ VIRTUAL_ENV=/Users/yshalsager/Library/Caches/pypoetry/virtualenvs/b-R0eeichC-py3.12
++ [[ -z /Users/yshalsager/Library/Caches/pypoetry/virtualenvs/b-R0eeichC-py3.12 ]]
++ [[ ! -d /Users/yshalsager/Library/Caches/pypoetry/virtualenvs/b-R0eeichC-py3.12 ]]
++ POETRY_ACTIVE=1
++ RTX_ADD_PATH=/Users/yshalsager/Library/Caches/pypoetry/virtualenvs/b-R0eeichC-py3.12/bin
++ export VIRTUAL_ENV POETRY_ACTIVE RTX_ADD_PATH
+ export -p
thread 'main' panicked at src/path_env.rs:39:35:
called `Result::unwrap()` on an `Err` value: JoinPathsError { inner: JoinPathsError }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by yshalsager** [comment]
@jdx apprently it was broken poetry env problem? after removing `/Users/yshalsager/Library/Caches/pypoetry/virtualenvs/b-R0eeichC-py3.12` everything works as previous.

**Comment by jdx** [comment]
strange, I see nothing wrong with that path

**Comment by yshalsager** [comment]
> strange, I see nothing wrong with that path

It's probably a broken env, IIRC I cancelled it while being created because I use local .venv managed by mise.

Sorry for the false report! Keep up the great work on mise!

**Comment by pablogamboa** [comment]
@jdx congrats on an amazing project. I've just been bitten by this bug, the fix is as yshalsager mentioned in his [last comment](https://github.com/jdx/mise/issues/1399#issuecomment-1881592095):

Remove `pyproject="pyproject.toml"` from the poetry definition, i.e.:

```diff
diff --git a/.mise.toml b/.mise.toml
index ab7cf2df3..18914a6a2 100644
--- a/.mise.toml
+++ b/.mise.toml
@@ -11,5 +11,61 @@ PGTZ = "UTC"
 [tools]
 java = "20"
 node = "18.18.0"
-poetry = {version="1.7.1", pyproject="pyproject.toml"}
+poetry = {version="1.7.1"}
```

**Comment by jdx** [comment]
it seems to work for me now, try updating mise-poetry
