### ISSUE TITLE
"mise run" bash completion with mise 2024.10.13 gives "Invalid usage config" with panic

### ISSUE THREAD

**Issue by gebailey** [jdx/mise#2874]
**Describe the bug**
After upgrading from mise-2024.10.12 to mise-2024.10.13, typing "mise run " and then pressing [TAB] (using bash completions) results in the following output:

```
$ mise run Error:   × Invalid usage config
thread 'main' panicked at library/std/src/io/mod.rs:1836:21:
a formatting trait implementation returned an error when the underlying stream did not
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
Install mise-2024.10.13
```
  eval "$(mise activate bash)"
  eval "$(mise completion bash)"

mise run <tab>
```

**Expected behavior**
I expected a list of possible tasks that could be completed, and this behavior is observed with mise-2024.10.12.

**`mise doctor` output**

```text
version: 2024.10.13 linux-x64 (ee83488 2024-10-28)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 28 Oct 2024 03:25:17 +0000
  Rust Version: rustc 1.81.0 (eeb90cda1 2024-09-04)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.2.26(1)-release (x86_64-redhat-linux-gnu)
  Copyright (C) 2022 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/git/stacksafeguard/api/.mise.toml

backends:
  cargo
  core
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:
  usage  https://github.com/jdx/mise-usage.git#fe3888a
  uv     https://github.com/asdf-community/asdf-uv.git#e100db2

toolset:
  usage@0.8.4
  uv@0.4.20

env_vars:
  MISE_SHELL=bash

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cache_prune_age = "30d"
  ci = false
  color = true
  debug = false
  disable_backends = []
  disable_default_registry = false
  disable_hints = []
  disable_tools = []
  experimental = true
  fetch_remote_versions_cache = "1h"
  fetch_remote_versions_timeout = "10s"
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = "30s"
  jobs = 8
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  libgit2 = true
  lockfile = false
  log_level = "info"
  not_found_auto_install = true
  paranoid = false
  pin = false
  plugin_autoupdate_last_check_duration = "7d"
  quiet = false
  raw = false
  trace = false
  trusted_config_paths = []
  use_versions_host = true
  verbose = false
  yes = false

  [cargo]
  binstall = true

  [node]

  [pipx]
  uvx = false

  [python]
  default_packages_file = "~/.default-python-packages"
  pyenv_repo = "https://github.com/pyenv/pyenv.git"
  venv_auto_create = false
  venv_stdlib = false

  [ruby]
  default_packages_file = "~/.default-gems"
  ruby_build_repo = "https://github.com/rbenv/ruby-build.git"
  ruby_install = false
  ruby_install_repo = "https://github.com/postmodern/ruby-install.git"

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false
No warnings found
No problems found
```

**Additional context**
Output of `mise completion bash` appears identical in both mise-2024.10.12 and mise-2024.10.13.

**Comment by jdx** [comment]
you need to update usage

**Comment by gebailey** [comment]
> you need to update usage

Ok, that does appear to fix it. How would I have known I needed to do this? Maybe I missed a release note? Or can `mise` check if plugins are outdated, etc.?

**Comment by h3adache** [comment]
It seems usage has been somehow responsible for ever break regarding mise since it was added as a dependency. Surely there's a better way?

**Comment by jdx** [comment]
mise does not use usage at all, it's only used for completions

**Comment by h3adache** [comment]
I understand what you mean but atm that means that I can run
```
mise self-update
mise <tab> # this breaks quite often.
```

There's no mention of needing to update usage or needing to keep mise in sync with some version of usage here.
https://mise.jdx.dev/cli/self-update.html

Nor does `mise doctor` tell you anything.
If `mise self-update` also update usage if needed that would be great.

The [homebrew formula](https://formulae.brew.sh/formula/mise) does this which is really nice but I think it's the only method listed on the installing page that actually does this.

Maybe I'll dogfood it for now by making a mise task to do this so myself and others I've recommended mise to don't keep forgetting. 😃

**Comment by dmorgan-fa** [comment]
I'm running into the same issue on the latest `mise` (installed via homebrew):

``` shell
─➤ mise --version
2024.11.4 macos-arm64 (2024-11-06)

# Attempt tab completion
─➤ mise Error:   × Invalid usage config
thread 'main' panicked at library/std/src/io/mod.rs:1836:21:
a formatting trait implementation returned an error when the underlying stream did not

─➤ mise doctor
version: 2024.11.4 macos-arm64 (2024-11-06)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Wed, 6 Nov 2024 22:16:42 +0000
  Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/Library/Caches/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/.config/mise/config.toml

backends:
  cargo
  core
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:
  terraform   https://github.com/asdf-community/asdf-hashicorp.git#22eb1c4
  terragrunt  https://github.com/ohmer/asdf-terragrunt.git#4a6651a
  usage       https://github.com/jdx/mise-usage.git#fe3888a

toolset:
  usage@0.11.0
  ruby@3.3.5
  terraform@1.9.6
  terragrunt@0.67.10
  node@20.12.2

env_vars:
  MISE_NODE_COREPACK=true
  MISE_SHELL=zsh

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cache_prune_age = "30d"
  ci = false
  color = true
  debug = false
  disable_backends = []
  disable_default_registry = false
  disable_hints = []
  disable_tools = []
  experimental = true
  fetch_remote_versions_cache = "1h"
  fetch_remote_versions_timeout = "10s"
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = "30s"
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  libgit2 = true
  lockfile = false
  log_level = "info"
  not_found_auto_install = true
  paranoid = false
  pin = false
  plugin_autoupdate_last_check_duration = "7d"
  quiet = false
  raw = false
  task_timings = false
  trace = false
  trusted_config_paths = []
  use_versions_host = true
  verbose = false
  yes = false

  [cargo]
  binstall = true

  [node]

  [pipx]
  uvx = false

  [python]
  default_packages_file = "~/.default-python-packages"
  pyenv_repo = "https://github.com/pyenv/pyenv.git"
  venv_auto_create = false
  venv_stdlib = false

  [ruby]
  default_packages_file = "~/.default-gems"
  ruby_build_repo = "https://github.com/rbenv/ruby-build.git"
  ruby_install = false
  ruby_install_repo = "https://github.com/postmodern/ruby-install.git"

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false
No warnings found
No problems found
```

**Comment by zachallaun** [comment]
I thought I had this fixed, but it seems to have cropped up again with the just-released v2024.11.12.

```
$ which usage
/home/zacha/.local/share/mise/installs/usage/1.2.0/bin/usage

$ mise h<TAB>
thread 'main' panicked at std/src/io/mod.rs:1832:21:
a formatting trait implementation returned an error when the underlying stream did not
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by syhol** [comment]
> It looks like https://github.com/jdx/mise/pull/2984 warns under different circumstances?

I think 1.3.0 will be the last usage version that won't print the warning as its 1.3.0 where the feature was added:
- https://github.com/jdx/usage/pull/166
- https://github.com/jdx/usage/pull/164
