### ISSUE TITLE
Having some trouble installing ruby gems

### ISSUE THREAD

**Issue by renatojf** [jdx/mise#2996]
```
mise exec ruby@3.3.5 --verbose -- gem install solargraph
DEBUG ARGS: .local/bin/mise exec ruby@3.3.5 --verbose -- gem install solargraph
DEBUG config: ~/.config/mise/config.toml
DEBUG EnvResults
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - asdf
        .local/share/mise/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:15:in ``'
        .local/share/mise/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:15:in `block (2 levels) in <top (required)>'
        .local/share/mise/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:14:in `each'
        .local/share/mise/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:14:in `block in <top (required)>'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/installer.rb:383:in `block in run_post_install_hooks'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/installer.rb:382:in `each'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/installer.rb:382:in `run_post_install_hooks'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/installer.rb:351:in `install'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/resolver/specification.rb:105:in `install'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/request_set.rb:195:in `block in install'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/request_set.rb:183:in `each'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/request_set.rb:183:in `install'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:207:in `install_gem'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:216:in `each'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:216:in `install_gems'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:162:in `execute'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/command_manager.rb:255:in `invoke_command'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/command_manager.rb:194:in `process_args'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/command_manager.rb:152:in `run'
        .local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
        .local/share/mise/installs/ruby/3.3.5/bin/gem:12:in `<main>'
```

Tried digging down into asdf-ruby to try to understand what's going on, but it seems to be that `mise` is the culprit. Couldn't find anywhere what could this be.
Any help? :)

**Comment by jdx** [comment]
you can't use asdf-ruby with mise

**Comment by renatojf** [comment]
when did this change? I had it configured like this for a long time, never realized it stopped working :(
I will switch my configs for the core plugin.. thanks @jdx

**Comment by jdx** [comment]
I don't think it ever worked

**Comment by renatojf** [comment]
well I can tell you it never failed me before.. I had solargraph configured with neovim using mise to install the dependencies and it started only failing recently

**Comment by skatkov** [comment]
Maybe you used system ruby previously?
