### ISSUE TITLE
File name too long when installing Python 3.8 on MacOS 15.2

### ISSUE THREAD

**Issue by joshuataylor** [jdx/mise#3846]
**Describe the bug**
Trying to install Python 3.8.12 on MacOS 15.1:

```sh
Looking in links: /var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/tmptu14_667
Processing /private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/tmptu14_667/setuptools-56.0.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 63] File name too long: '/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/pip-req-tracker-lq8prlo_/c0091313ab27c45bd27e9c7fc5bf4bf4ae46b5793f3b9ec3a169cce60000000000791602010000003003926f010000005876a80001000000040000000000000000003b5cae20095d380bc600010000003088c900010000004835c2010100000000791602010000008003926f010000003884a300010000007003926f010000000c75a800010000008003926f0100000024f7a6000000000001000000000000004835c2010100000000791602010000000000000000000000507ae029010000009004926f01000000d003926f010000007c91af000100000000000000000000005035c2010100000010c57302010000007041070301000000a10000000000000012c5730201000000c033c2010100000000c57302010000004005926f01000000445faf00010000002004926f01000000640db500010000002004926f01000000700fb500010000000047590201000000b0671a0301000000d0f3b60101000000406d73020100000000000000ffffffff2835c2010100000000000000000000004035c20101000000ffffffff0000000000a2b60101000000000000000000000000c5730201000000507ae02901000000c869a700010000005823c50001000000406d730201000000c004926f01000000640db500010000005035c201010000000079160201000000809c5b000100000007000000000000005823c50001000000406d730201000000f004926f01000000700fb5000100000000003b5cae20095d4030a7010100000000000000000000000100000000000000507ae029010000003088c90001000000d8633e0301000000e8633e030100000002000000000000003088c90001000000f0633e03010000000000000000000000c033c20101000000507ae029010000008005926f0100000078f1a2000100000002000000000000'

Traceback (most recent call last):
  File "/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/python-build.20241227233620.60583/Python-3.8.12/Lib/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/python-build.20241227233620.60583/Python-3.8.12/Lib/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/python-build.20241227233620.60583/Python-3.8.12/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/python-build.20241227233620.60583/Python-3.8.12/Lib/ensurepip/__init__.py", line 206, in _main
    return _bootstrap(
  File "/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/python-build.20241227233620.60583/Python-3.8.12/Lib/ensurepip/__init__.py", line 125, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/python-build.20241227233620.60583/Python-3.8.12/Lib/ensurepip/__init__.py", line 34, in _run_pip
    return subprocess.run([sys.executable, "-c", code], check=True).returncode
  File "/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/python-build.20241227233620.60583/Python-3.8.12/Lib/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/python-build.20241227233620.60583/Python-3.8.12/python.exe', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/tmptu14_667/setuptools-56.0.0-py3-none-any.whl\', \'/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/tmptu14_667/pip-21.1.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d6/y0bbdlcx5h5dgqgkr33d1sww0000gn/T/tmptu14_667\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [Makefile:1198: install] Error 1
```

On Debian 12, it seems to work:

```sh
INFO  python@3.8.12    PYTHONPATH=/home/josh/.local/share/mise/installs/python/3.8.12/lib/python3.8 LD_LIBRARY_PATH=/tmp/python-build.20241227234207.1281177/Python-3.8.12 \
```

.mise.toml:

```toml
[tools]
# Python 3.8.12
# https://www.sublimetext.com/docs/api_environments.html#selecting-the-python-version
python = {version='3.8.12', virtualenv='.venv'}
```

**To Reproduce**
1. MacOS 15.2 ARM64 (m2) (24C101)
2. `mise --version` `2024.12.20 macos-arm64 (2024-12-25)`

**Expected behavior**

Python 3.8.12 compiles on MacOS.

**`mise doctor` output**

```text
version: 2024.12.20 macos-arm64 (2024-12-25)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Wed, 25 Dec 2024 20:45:03 +0000
  Rust Version: rustc 1.83.0 (90b35a623 2024-11-26) (Homebrew)
  Profile: release

shell:
  /opt/homebrew/bin/zsh
  zsh 5.9.0.1-dev (arm-apple-darwin24.1.0)

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml
  ~/dev/sublime_toggle_case_plugin/.mise.toml

ignored_config_files: (none)

backends:
  aqua
  asdf
  cargo
  core
  dotnet
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:
  poetry  https://github.com/mise-plugins/mise-poetry.git#daaaab6

toolset:
  core:python@3.8.12  (missing)

path:
  ~/.bin
  ~/.cargo/bin
  /opt/homebrew/opt/coreutils/libexec/gnubin
  /opt/homebrew/opt/ed/libexec/gnubin
  /opt/homebrew/opt/findutils/libexec/gnubin
  /opt/homebrew/opt/gawk/libexec/gnubin
  /opt/homebrew/opt/gnu-indent/libexec/gnubin
  /opt/homebrew/opt/gnu-sed/libexec/gnubin
  /opt/homebrew/opt/gnu-tar/libexec/gnubin
  /opt/homebrew/opt/gnu-which/libexec/gnubin
  /opt/homebrew/opt/grep/libexec/gnubin
  /opt/homebrew/opt/gsed/libexec/gnubin
  /opt/homebrew/opt/make/libexec/gnubin
  /opt/homebrew/opt/sqlite/bin
  ~/.config/jetbrains
  /opt/homebrew/opt/postgresql@16/bin
  /opt/homebrew/bin
  /opt/homebrew/sbin
  ~/.nix-profile/bin
  /nix/var/nix/profiles/default/bin
  /usr/local/bin
  /System/Cryptexes/App/usr/bin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
  /Library/Apple/usr/bin

env_vars:
  MISE_SHELL=zsh

settings:
  disable_hints         ["python_multi"]              ~/.config/mise/config.toml
  experimental          true                          ~/.config/mise/config.toml
  jobs                  1                             ~/.config/mise/config.toml
  python.uv_venv_auto   true                          ~/.config/mise/config.toml
  python_compile        true                          ~/.config/mise/config.toml
  status.missing_tools  "if_other_versions_installed" ~/.config/mise/config.toml

No problems found
```

**Additional context**

Seems like mise might need to check the max length for paths for tmp installs, I've ran into similar problems with my SSHControlPath on MacOS being too long without much effort.

**Comment by jdx** [comment]
this doesn't seem to be related to mise
